/**
 * Konfigurasi situs global dan SEO untuk Bincang Edukasi
 */
export const siteConfig = {
  name: 'Bincang Edukasi',
  tagline: 'Siap Hadapi Ujian',
  siteUrl: 'https://bincangedukasi.com',
  title: 'Bincang Edukasi | Bimbel Masuk UI, Bimbel SNBT & Supercamp SIMAK KKI UI Terpercaya',
  description: 'Bimbingan belajar spesialis Bimbel Masuk UI, Bimbel SNBT, Bimbel Simak UI, Supercamp SIMAK KKI UI, dan Bimbel PTN Favorit dengan Master Tutor lulusan Universitas Indonesia dan tingkat kelulusan >90%.',
  keywords: [
    'Bimbel PTN',
    'Bimbel SNBT',
    'Supercamp SIMAK KKI UI',
    'Bimbel Simak UI',
    'Bimbel Masuk UI',
    'Bimbel Kedokteran UI',
    'Bimbel KKI UI',
    'Karantina SNBT',
    'Tryout UTBK SNBT',
    'Bimbingan Belajar PTN Terbaik',
  ],
  author: 'Bincang Edukasi',
  ogImage: '/logo.png',
  navLinks: [
    { label: 'Beranda', href: '/' },
    { label: 'Program Unggulan', href: '/#program' },
    { label: 'Kontak Kami', href: '/#kontak' },
  ],
  channels: [
    {
      id: 'pendaftaran',
      title: 'Pendaftaran WhatsApp',
      label: 'wa.me/6285890306392',
      url: 'https://wa.me/6285890306392',
      category: 'Layanan Utama',
      description: 'Konsultasi dan pendaftaran resmi via WhatsApp',
      type: 'whatsapp',
      badge: 'Resmi',
      highlight: true,
    },
    {
      id: 'buku-ptn',
      title: 'Buku Jurus Masuk PTN',
      label: 'shopee.co.id/jurusmasukptn_2026',
      url: 'https://shopee.co.id/jurusmasukptn_2026',
      category: 'Buku Fisik & Modul',
      description: 'Buku cetak panduan lolos seleksi PTN terbaru di Shopee',
      type: 'shopee',
      badge: 'Best Seller',
    },
    {
      id: 'ebook',
      title: 'Edisi Ebook',
      label: 'lynk.id/pusatbukuedukasi_/41klrw1l14yo',
      url: 'https://lynk.id/pusatbukuedukasi_/41klrw1l14yo',
      category: 'Materi Digital',
      description: 'Akses instan modul belajar digital via Lynk.id',
      type: 'ebook',
      badge: 'Instan Download',
    },
    {
      id: 'tiktok',
      title: 'TikTok',
      label: 'tiktok.com/@bincangedukasi',
      url: 'https://www.tiktok.com/@bincangedukasi',
      category: 'Media Sosial',
      description: 'Tips belajar, bedah soal, dan video motivasi ujian',
      type: 'tiktok',
    },
    {
      id: 'instagram',
      title: 'Instagram',
      label: 'instagram.com/bincangedu',
      url: 'https://www.instagram.com/bincangedu/',
      category: 'Media Sosial',
      description: 'Informasi tryout, jadwal live, & tips edukasi',
      type: 'instagram',
    },
    {
      id: 'x',
      title: 'X (Twitter)',
      label: 'x.com/bincangedukasi_',
      url: 'https://x.com/bincangedukasi_?t=M6EmR_jcf40qknfwv0zJhw&s=08',
      category: 'Media Sosial',
      description: 'Diskusi seputar soal dan update pendidikan terkini',
      type: 'x',
    },
  ],
  contacts: {
    whatsapp: 'https://wa.me/6285890306392',
    phone: '+62 858-9030-6392',
    email: 'info@bincangedukasi.com',
    address: 'Indonesia',
  },
};
